### ISSUE TITLE
Github Pages not working

### ISSUE THREAD

**Issue by Czeksu** [Zryp9x/COVID-19-APP#4]
Issue with /dist/build.js
[https://zryp9x.github.io/COVID-19-APP/](url)
![image](https://user-images.githubusercontent.com/47739763/80201997-43f0fc00-8625-11ea-9216-9cd7f00016f6.png)

**Comment by Zryp9x** [comment]
updated index in gh-pages branch with build path "/COVID-19-APP/build.js"
