### ISSUE TITLE
Reload error

### ISSUE THREAD

**Issue by Zryp9x** [Zryp9x/COVID-19-APP#6]
Error 404 after reloading
![Przechwytywanie11](https://user-images.githubusercontent.com/47739749/80253585-de7b2a80-8679-11ea-885c-ca749a72275e.PNG)

**Comment by Czeksu** [comment]
Fixed by changing mode from:
`const router = new VueRouter({
    routes,
    mode: 'history'
});`
to:
`const router = new VueRouter({
    routes,
    mode: 'hash'
});`
